
graph TD
    A[Bot Creator] --> B(.env)
    A --> C(config)
    A --> D(docker-compose.yml)
    D --> E[Docker Bot 1]
    D --> F[Docker Bot 2]
    D --> G[Docker Bot 3]
    E --> H[API Dash]
    F --> H
    G --> H
    H --> I[Frontend]

